# Week-01 : NumPy

In [26]:
import numpy as np

1. Convert a 1-D array into a 2-D array with 3 rows.

In [27]:
a1 = np.arange(9).reshape(3,3)
a1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

2. Replace all odd numbers in the given array with -1


In [25]:
a2 = np.arange(10)
print(a2)
result = np.where(a2 % 2 == 0, a2, -1)
print(result)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


3. Find the positions of:
elements in x where its value is more than its corresponding element in y, and elements in x where its value is
equals to its corresponding element in y.

In [29]:
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89])
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])
greater = np.where(x > y)
equal = np.where(x == y)
print(greater)
equal

(array([1, 2, 4, 5, 6, 7, 8, 9]),)


(array([0]),)

4. Extract the first four columns of this 2-D array.

In [30]:
assign_4 = np.arange(100).reshape(5, -1)
result = assign_4[:, :4]
result

array([[ 0,  1,  2,  3],
       [20, 21, 22, 23],
       [40, 41, 42, 43],
       [60, 61, 62, 63],
       [80, 81, 82, 83]])

# ADDITIONAL

1. Generate a 1-D array of 10 random integers. Each integer should be a number between 30 and 40 (inclusive).

In [35]:
aa1 = np.random.randint(0, 100, size=10)
aa1

array([71, 54, 23, 60, 57, 26, 89, 92, 24, 59])

2. Consider the following matrices : <br>
A= ((1, 2, 3), (4, 5, 6), (7, 8, 10)) and B = ((7, 8, 10) ,(4, 5, 6), (1, 2, 3))<br>
Write a python program to perform the following using Numeric Python (numpy).<br>
i) Add and Subtract of the Matrix A and B, print the resultant matrix C for add and E for subtract.
<br>ii) Compute the sum of all elements of Matrix A, sum of each column of Matrix B and sum of each row of Matrix C
<br>iii) Product of two matrices A and B, and print the resultant matrix D
<br>iv) Sort the elements of resultant matrix C and print the resultant Matrix E.
<br>v) Transpose the Matrix E and print the result

In [40]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 10]])
B = np.array([[7, 8, 10], [4, 5, 6], [1, 2, 3]])

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)
#i
C = A + B
E_sub = A - B
print("Resultant Matrix C (Add):\n", C)
print("Resultant Matrix E (Subtract):\n", E_sub)

# ii
sum_A = np.sum(A)
sum_col_B = np.sum(B, axis=0) 
sum_row_C = np.sum(C, axis=1) 
print("Sum of all elements of Matrix A:", sum_A)
print("Sum of each column of Matrix B:", sum_col_B)
print("Sum of each row of Matrix C:", sum_row_C)

# iii
D = np.dot(A, B) 
print("Resultant Matrix D (Product):\n", D)

# iv
E = np.sort(C)
print("Resultant Matrix E:\n", E)

# v
E_trans = E.T
print("Resultant Transposed Matrix:\n", E_trans)


Matrix A:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]

Matrix B:
 [[ 7  8 10]
 [ 4  5  6]
 [ 1  2  3]]
Resultant Matrix C (Add):
 [[ 8 10 13]
 [ 8 10 12]
 [ 8 10 13]]
Resultant Matrix E (Subtract):
 [[-6 -6 -7]
 [ 0  0  0]
 [ 6  6  7]]
Sum of all elements of Matrix A: 46
Sum of each column of Matrix B: [12 15 19]
Sum of each row of Matrix C: [31 30 31]
Resultant Matrix D (Product):
 [[ 18  24  31]
 [ 54  69  88]
 [ 91 116 148]]
Resultant Matrix E:
 [[ 8 10 13]
 [ 8 10 12]
 [ 8 10 13]]
Resultant Transposed Matrix:
 [[ 8  8  8]
 [10 10 10]
 [13 12 13]]
